version: '3.8'

services:
  backend:
    build:
      context: ./Back-End/Back-End-Winku
      dockerfile: Dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./Back-End/Back-End-Winku:/var/www/html
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel-api
      DB_USERNAME: root
      DB_PASSWORD: rootroot7
    depends_on:
      - mysql

#  frontend:
#    build:
#      context: ./Front-End
#      dockerfile: Dockerfile
#    ports:
#      - '3000:3000'
#    volumes:
#      - ./Front-End:/var/www
#    command: npm run dev

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-api
      MYSQL_USER: root
      MYSQL_PASSWORD: rootroot7
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3307:3306'  # Change host port to 3307

volumes:
  mysql_data:

