version: "3"
services:
    laravel:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
            args:
                WWWGROUP: '1000'
        image: sail-8.0/app
        ports:
            - '81:80'
        environment:
            WWWUSER: 'user'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        ports:
            - '3000:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'laravel'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping" ]
networks:
    sail:
        driver: bridge
